# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "bazil.org/fuse"

[[constraint]]
  name = "github.com/Kubuxu/go-os-helper"
  version = "0.0.1"

[[constraint]]
  branch = "master"
  name = "github.com/Kubuxu/gocovmerge"

[[constraint]]
  name = "github.com/blang/semver"
  version = "3.6.1"

[[constraint]]
  branch = "master"
  name = "github.com/bren2010/proquint"

[[constraint]]
  name = "github.com/cenkalti/backoff"
  version = "3.0.0"

[[constraint]]
  name = "github.com/dustin/go-humanize"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/elgris/jsondiff"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "1.2.1"

[[constraint]]
  name = "github.com/golangci/golangci-lint"
  version = "1.17.1"

[[constraint]]
  name = "github.com/hashicorp/go-multierror"
  version = "1.0.0"

[[constraint]]
  name = "github.com/hashicorp/golang-lru"
  version = "0.5.1"

[[constraint]]
  name = "github.com/hsanjuan/go-libp2p-http"
  version = "0.1.2"

[[constraint]]
  name = "github.com/ipfs/dir-index-html"
  version = "1.0.3"

[[constraint]]
  name = "github.com/ipfs/go-bitswap"
  version = "0.1.1"

[[constraint]]
  name = "github.com/ipfs/go-block-format"
  version = "0.0.2"

[[constraint]]
  name = "github.com/ipfs/go-blockservice"
  version = "0.1.0"

[[constraint]]
  name = "github.com/ipfs/go-cid"
  version = "0.0.2"

[[constraint]]
  name = "github.com/ipfs/go-cidutil"
  version = "0.0.2"

[[constraint]]
  name = "github.com/ipfs/go-datastore"
  version = "0.0.5"

[[constraint]]
  name = "github.com/ipfs/go-detect-race"
  version = "0.0.1"

[[constraint]]
  name = "github.com/ipfs/go-ds-badger"
  version = "0.0.3"

[[constraint]]
  name = "github.com/ipfs/go-ds-flatfs"
  version = "0.0.2"

[[constraint]]
  name = "github.com/ipfs/go-ds-leveldb"
  version = "0.0.2"

[[constraint]]
  name = "github.com/ipfs/go-ds-measure"
  version = "0.0.1"

[[constraint]]
  name = "github.com/ipfs/go-fs-lock"
  version = "0.0.1"

[[constraint]]
  name = "github.com/ipfs/go-ipfs-blockstore"
  version = "0.0.1"

[[constraint]]
  name = "github.com/ipfs/go-ipfs-blocksutil"
  version = "0.0.1"

[[constraint]]
  name = "github.com/ipfs/go-ipfs-chunker"
  version = "0.0.1"

[[constraint]]
  name = "github.com/ipfs/go-ipfs-cmds"
  version = "0.0.10"

[[constraint]]
  name = "github.com/ipfs/go-ipfs-config"
  source = "github.com/vulcanize/go-ipfs-config"
  revision = "4a51393611d9580d17ecbccb0c4aec5eb81f21ce"

[[constraint]]
  name = "github.com/ipfs/go-ipfs-ds-help"
  version = "0.0.1"

[[constraint]]
  name = "github.com/ipfs/go-ipfs-exchange-interface"
  version = "0.0.1"

[[constraint]]
  name = "github.com/ipfs/go-ipfs-exchange-offline"
  version = "0.0.1"

[[constraint]]
  name = "github.com/ipfs/go-ipfs-files"
  version = "0.0.3"

[[constraint]]
  name = "github.com/ipfs/go-ipfs-posinfo"
  version = "0.0.1"

[[constraint]]
  name = "github.com/ipfs/go-ipfs-routing"
  version = "0.1.0"

[[constraint]]
  name = "github.com/ipfs/go-ipfs-util"
  version = "0.0.1"

[[constraint]]
  name = "github.com/ipfs/go-ipld-cbor"
  version = "0.0.2"

[[constraint]]
  name = "github.com/ipfs/go-ipld-format"
  version = "0.0.2"

[[constraint]]
  name = "github.com/ipfs/go-ipld-git"
  version = "0.0.2"

[[constraint]]
  name = "github.com/ipfs/go-ipns"
  version = "0.0.1"

[[constraint]]
  name = "github.com/ipfs/go-log"
  version = "0.0.1"

[[constraint]]
  name = "github.com/ipfs/go-merkledag"
  version = "0.1.0"

[[constraint]]
  name = "github.com/ipfs/go-metrics-interface"
  version = "0.0.1"

[[constraint]]
  name = "github.com/ipfs/go-metrics-prometheus"
  version = "0.0.2"

[[constraint]]
  name = "github.com/ipfs/go-mfs"
  version = "0.1.0"

[[constraint]]
  name = "github.com/ipfs/go-path"
  version = "0.0.7"

[[constraint]]
  name = "github.com/ipfs/go-unixfs"
  version = "0.0.8"

[[constraint]]
  name = "github.com/ipfs/go-verifcid"
  version = "0.0.1"

[[constraint]]
  name = "github.com/ipfs/hang-fds"
  version = "0.0.1"

[[constraint]]
  name = "github.com/ipfs/interface-go-ipfs-core"
  version = "0.1.0"

[[constraint]]
  name = "github.com/ipfs/iptb"
  version = "1.4.0"

[[constraint]]
  name = "github.com/ipfs/iptb-plugins"
  version = "0.1.0"

[[constraint]]
  name = "github.com/jbenet/go-is-domain"
  version = "1.0.2"

[[constraint]]
  branch = "master"
  name = "github.com/jbenet/go-random"

[[constraint]]
  branch = "master"
  name = "github.com/jbenet/go-random-files"

[[constraint]]
  branch = "master"
  name = "github.com/jbenet/go-temp-err-catcher"

[[constraint]]
  name = "github.com/jbenet/goprocess"
  version = "0.1.3"

[[constraint]]
  name = "github.com/libp2p/go-libp2p"
  version = "0.1.1"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-autonat-svc"
  version = "0.1.0"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-circuit"
  version = "0.1.0"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-connmgr"
  version = "0.1.0"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-core"
  version = "0.0.3"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-kad-dht"
  version = "0.1.0"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-kbucket"
  version = "0.2.0"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-loggables"
  version = "0.1.0"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-mplex"
  version = "0.2.1"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-peerstore"
  version = "0.1.0"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-pnet"
  version = "0.1.0"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-pubsub"
  version = "0.1.0"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-pubsub-router"
  version = "0.1.0"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-quic-transport"
  version = "0.1.1"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-record"
  version = "0.1.0"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-routing-helpers"
  version = "0.1.0"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-secio"
  version = "0.1.0"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-swarm"
  version = "0.1.0"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-testing"
  version = "0.0.4"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-tls"
  version = "0.1.0"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-yamux"
  version = "0.2.1"

[[constraint]]
  name = "github.com/libp2p/go-maddr-filter"
  version = "0.0.4"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.1.0"

[[constraint]]
  name = "github.com/mr-tron/base58"
  version = "1.1.2"

[[constraint]]
  name = "github.com/multiformats/go-multiaddr"
  version = "0.0.4"

[[constraint]]
  name = "github.com/multiformats/go-multiaddr-dns"
  version = "0.0.2"

[[constraint]]
  name = "github.com/multiformats/go-multiaddr-net"
  version = "0.0.1"

[[constraint]]
  name = "github.com/multiformats/go-multibase"
  version = "0.0.1"

[[constraint]]
  name = "github.com/multiformats/go-multihash"
  version = "0.0.5"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.1.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.4"

[[constraint]]
  name = "github.com/syndtr/goleveldb"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/whyrusleeping/base32"

[[constraint]]
  branch = "master"
  name = "github.com/whyrusleeping/go-sysinfo"

[[constraint]]
  branch = "master"
  name = "github.com/whyrusleeping/multiaddr-filter"

[[constraint]]
  branch = "master"
  name = "github.com/whyrusleeping/tar-utils"

[[constraint]]
  name = "go.uber.org/fx"
  version = "1.9.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sys"

[[constraint]]
  name = "gopkg.in/cheggaaa/pb.v1"
  version = "1.0.28"

[[constraint]]
  name = "gotest.tools/gotestsum"
  version = "0.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/whyrusleeping/sql-datastore"

[[override]]
  name = "github.com/dgraph-io/badger"
  revision = "0ce1d2e26af1ba8b8a72ea864145a3e1e3b382cd"

[prune]
  go-tests = true
  unused-packages = true
